# Generated by Django 2.2.5 on 2019-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulUchetchik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineinoffice',
            options={'verbose_name': 'Очарад корхонаба', 'verbose_name_plural': 'Очарадхо корхонаба'},
        ),
        migrations.AddField(
            model_name='lineinoffice',
            name='occuredTime',
            field=models.CharField(max_length=100,default='2019-09-20 13:55:47',  verbose_name='Ахиранги хизмата вакташ'),
        ),
        migrations.AlterField(
            model_name='lineinoffice',
            name='addressOfOffice',
            field=models.CharField(max_length=200, verbose_name='Корхоная манзилаш/ориентир'),
        ),
        migrations.AlterField(
            model_name='lineinoffice',
            name='alias',
            field=models.CharField(max_length=100, verbose_name='Корхоная калта номаш'),
        ),
        migrations.AlterField(
            model_name='lineinoffice',
            name='numberToCount',
            field=models.IntegerField(verbose_name='Раками навбат'),
        ),
    ]
